# Generated by Django 5.0.3 on 2024-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_viewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcount',
            options={'ordering': ('-viewed_on',), 'verbose_name': 'Просмотр', 'verbose_name_plural': 'Просмотры'},
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['-viewed_on'], name='blog_viewco_viewed__0b448b_idx'),
        ),
    ]
