# Generated by Django 5.0.3 on 2024-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Электронный адрес (email)'),
        ),
    ]
